name: better_one
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.4
  dio: ^5.4.1
  easy_localization: ^3.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_local_notifications: ^17.2.1+2
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  flutter_timezone: ^2.1.0
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  hive_flutter: ^1.1.0
  intl: 0.19.0
  json_annotation: ^4.8.1
  smooth_page_indicator: ^1.1.0
  timezone: ^0.9.2
  logger: ^2.0.2+1
  lottie: ^3.1.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  feedback: ^3.0.1
  device_info_plus: ^10.1.1
  package_info_plus: ^8.0.1
  uuid: ^4.4.0
  go_router: ^14.2.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_messaging: ^15.0.4
  cloud_firestore: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - lib/l10n/translation/
    - assets/lottie/
    - assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf